name: taskbinge
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - python=3.10.15
  - readline=8.2
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - annotated-types==0.7.0
    - anyio==4.6.2.post1
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - distro==1.9.0
    - exceptiongroup==1.2.2
    - filelock==3.16.1
    - fsspec==2024.10.0
    - ftfy==6.3.1
    - h11==0.14.0
    - httpcore==1.0.6
    - httpx==0.27.2
    - huggingface-hub==0.26.2
    - idna==3.10
    - jinja2==3.1.4
    - jiter==0.7.0
    - joblib==1.4.2
    - llvmlite==0.43.0
    - markupsafe==3.0.2
    - more-itertools==10.5.0
    - mpmath==1.3.0
    - networkx==3.4.2
    - numba==0.60.0
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - openai==1.53.0
    - openai-whisper==20240930
    - packaging==24.1
    - pillow==11.0.0
    - pip==24.2
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pysbd==0.3.4
    - pyyaml==6.0.2
    - regex==2024.9.11
    - requests==2.32.3
    - safetensors==0.4.5
    - scikit-learn==1.5.2
    - scipy==1.14.1
    - sentence-transformers==3.2.1
    - setuptools==75.1.0
    - sniffio==1.3.1
    - sympy==1.13.1
    - threadpoolctl==3.5.0
    - tiktoken==0.8.0
    - tokenizers==0.20.1
    - torch==2.5.1
    - torchvision==0.20.1
    - tqdm==4.66.6
    - transformers==4.46.1
    - triton==3.1.0
    - typing-extensions==4.12.2
    - urllib3==2.2.3
    - wcwidth==0.2.13
    - websockets==13.1
    - wheel==0.44.0
    - yt-dlp==2024.10.22
